//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJECT_NetGameVN_STINGDAU
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class quanlynetEntities : DbContext
    {
        public quanlynetEntities()
            : base("name=quanlynetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MayTinh> MayTinhs { get; set; }
        public virtual DbSet<MoMay> MoMays { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
