//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJECT_NetGameVN_STINGDAU
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoMay
    {
        public int id { get; set; }
        public int may_tinh_id { get; set; }
        public System.TimeSpan time_mo { get; set; }
    
        public virtual MayTinh MayTinh { get; set; }
    }
}
