//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJECT_NetGameVN_STINGDAU
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int Id { get; set; }
        public string ten_dang_nhap { get; set; }
        public string mat_khau { get; set; }
        public string so_dien_thoai { get; set; }
        public string ho_ten { get; set; }
        public double naptien { get; set; }
    }
}
