//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJECT_NetGameVN_STINGDAU.DPContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NetGameVNEntities1 : DbContext
    {
        public NetGameVNEntities1()
            : base("name=NetGameVNEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbAdmin> tbAdmins { get; set; }
        public virtual DbSet<tbClient> tbClients { get; set; }
        public virtual DbSet<tbGroupClient> tbGroupClients { get; set; }
        public virtual DbSet<tbGroupUser> tbGroupUsers { get; set; }
        public virtual DbSet<tbLoginUser> tbLoginUsers { get; set; }
        public virtual DbSet<tbMember> tbMembers { get; set; }
    }
}
