//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJECT_NetGameVN_STINGDAU.DPContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAdmin
    {
        public int Id_admin { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string fullname { get; set; }
        public string GroupUser { get; set; }
        public Nullable<bool> isLock { get; set; }
    
        public virtual tbGroupUser tbGroupUser { get; set; }
    }
}
