//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJECT_NetGameVN_STINGDAU.DPContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbMember
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbMember()
        {
            this.tbLoginUsers = new HashSet<tbLoginUser>();
        }
    
        public int MemberID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Phone { get; set; }
        public string GroupUser { get; set; }
        public Nullable<System.TimeSpan> CurrentTime { get; set; }
        public Nullable<double> CurrentMoney { get; set; }
        public string StatusAccount { get; set; }
        public string Fullname { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
    
        public virtual tbGroupUser tbGroupUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbLoginUser> tbLoginUsers { get; set; }
    }
}
