USE [master]
GO

/****** Object:  Database [NetGameVN]    Script Date: 26/10/2023 1:58:55 SA ******/
CREATE DATABASE [NetGameVN]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'NetGameVN', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MAYAO\MSSQL\DATA\NetGameVN.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'NetGameVN_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MAYAO\MSSQL\DATA\NetGameVN_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [NetGameVN].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [NetGameVN] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [NetGameVN] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [NetGameVN] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [NetGameVN] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [NetGameVN] SET ARITHABORT OFF 
GO

ALTER DATABASE [NetGameVN] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [NetGameVN] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [NetGameVN] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [NetGameVN] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [NetGameVN] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [NetGameVN] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [NetGameVN] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [NetGameVN] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [NetGameVN] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [NetGameVN] SET  DISABLE_BROKER 
GO

ALTER DATABASE [NetGameVN] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [NetGameVN] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [NetGameVN] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [NetGameVN] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [NetGameVN] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [NetGameVN] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [NetGameVN] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [NetGameVN] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [NetGameVN] SET  MULTI_USER 
GO

ALTER DATABASE [NetGameVN] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [NetGameVN] SET DB_CHAINING OFF 
GO

ALTER DATABASE [NetGameVN] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [NetGameVN] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [NetGameVN] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [NetGameVN] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [NetGameVN] SET QUERY_STORE = OFF
GO

ALTER DATABASE [NetGameVN] SET  READ_WRITE 
GO


